In [1]:
import pandas as pd
from makeRawData import makeRaceData,makeHorseData

In [2]:
horseIDList = []
horseIDList.append("2017106490")
horseIDList

['2017106490']

In [3]:
MHD = makeHorseData(horseIDList)

1頭の馬の過去成績/血統表データを作成します。

In [4]:
MHD.getHorseHTML(skipResult=False, skipPED=False)

getHorseHTML: 100%|██████████| 1/1 [00:04<00:00,  4.39s/it, horseID=2017106490(血統表)]

In [5]:
MHD.makeHorseRawData(skipResult=False, skipPED=False)

makeHorseRawData: 100%|██████████| 1/1 [00:00<00:00,  2.02it/s, horseID=2017106490(血統情報)]

1頭の馬の過去成績/血統表データを作成しました。

In [11]:
import random
import requests

In [9]:
def makeUserAgents():
    """
    USER_AGENTSのリストを返す関数
    Returns:
        list: USER_AGENTSのリスト
    """
    returnList = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:115.0) Gecko/20100101 Firefox/115.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:115.0) Gecko/20100101 Firefox/115.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.0.0",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 OPR/85.0.4341.72",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 OPR/85.0.4341.72",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Vivaldi/5.3.2679.55",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Vivaldi/5.3.2679.55",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Brave/1.40.107",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Brave/1.40.107",
    ]

    return returnList

In [28]:
url = "https://db.netkeiba.com/horse/" + "2007110038"
headers = {'User-Agent': random.choice(makeUserAgents())}
html = requests.get(url, headers=headers)
html.encoding = "EUC-JP"

In [29]:
html.text

'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja" id="html">\n<head>\n\n<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n<meta http-equiv="content-type" content="text/html; charset=euc-jp" />\n<meta http-equiv="content-script-type" content="text/javascript" />\n<meta http-equiv="content-style-type" content="text/css" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/reset.css?20160421" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/common.css?20210819" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/db_detail.css?20180621" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/horse_detail.css?20250620" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/win.css?20160421" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/db_top.css?20160421" rel="stylesheet" type="text/css" media="all" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/prettyPhoto.css?20160421" rel="stylesheet" type="text/css" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/jquery.fancybox-1.3.4.css?20160421" rel="stylesheet" type="text/css" />\n<link href="https://cdn.netkeiba.com/img.db/common/css/db_classic_nk01.css?201911209" rel="stylesheet" type="text/css" />\n<!-- link rel="stylesheet" href="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/css/common_header.css" type="text/css" -->\n<script language="javascript">\n<!--\nb = navigator.userAgent.toUpperCase();\nif(b.indexOf("MAC") >= 0)\n{\ncssFile = "mac.css";\n}\nelse\n{\ncssFile = "win.css";\n}\ndocument.write("<link rel=\'stylesheet\' type=\'text/css\' href=\'https://cdn.netkeiba.com/img.db/common/css/" + cssFile + "\'>");\n// -->\n</script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery-1.8.2.min.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.cookie.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/fontsize.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.prettyPhoto.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.fieldtag.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/table_hover.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.fancybox-1.3.4.pack.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.easing-1.3.pack.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.carouFredSel-6.2.0-packed.js?20160421"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.touchSwipe.min.js?20160421"></script>\n<link rel="stylesheet" type="text/css" href="https://cdn.netkeiba.com/img.db/common/css/ajaxtabs.css?20160421" />\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/ajaxtabs.js?20160421">\n/***********************************************\n* Ajax Tabs Content script v2.2- c Dynamic Drive DHTML code library (www.dynamicdrive.com)\n* This notice MUST stay intact for legal use\n* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code\n***********************************************/\n</script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/get_ad_request.js"></script>\n<script type="text/javascript">\n<!--\nvar _user_action_api_url    = \'https://cdn.netkeiba.com/img.user\';\nvar _newsapi_action_api_url = \'https://cdn.netkeiba.com/img.newsapi/\';\nvar _social_action_api_url  = \'https://cdn.netkeiba.com/img.db/\';\nvar _bbs_action_api_url     = \'https://bbs.netkeiba.com/\';\n// -->\n</script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.user/common/js/user.action.js?2016042101"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.newsapi//common/js/newsapi.action.js?2016042101"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db//common/js/social.action.js"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.bbs/common/js/bbs.action.js?2018053101"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.regist.sp//common/js/monthly_goods_link.js?2017080201"></script>\n\n<meta http-equiv="content-language" content="ja">\n<meta name="viewport" content="width=device-960px">\n<meta name="format-detection" content="telephone=no" />\n<meta name="description" content="クレバーロッシー (Clever Rossi)の競走馬データです。競走成績、血統情報、産駒情報などをはじめ、50万頭以上の競走馬・騎手・調教師・馬主・生産者・レースの全データがご覧いただけます。" />\n<meta name="keywords" content="競馬情報,競走馬,騎手,レース,調教師,馬主,検索,データベース,JRA,netkeiba,ネット競馬" />\n<meta name="thumbnail" content="https://cdn.netkeiba.com/img.db.sp/show_photo.php?horse_id=2007110038&no=spdb&tn=&tmp=no&default_image=netkeiba" />\n<!-- ogp用 -->\n<meta property="og:site_name" content="netkeiba" />\n<meta property="og:type" content="article" />\n<meta property="og:title" content="クレバーロッシー (Clever Rossi) | 競走馬データ - netkeiba" />\n<meta property="og:url" content="https://db.netkeiba.com/horse/2007110038/" />\n<meta property="og:description" content="クレバーロッシー (Clever Rossi)の競走馬データです。競走成績、血統情報、産駒情報などをはじめ、50万頭以上の競走馬、騎手・調教師・馬主・生産者の全データがご覧いただけます。" />\n<meta property="og:image" content="https://cdn.netkeiba.com/img.db.sp/show_photo.php?horse_id=2007110038&no=spdb&tn=&tmp=no&default_image=netkeiba" />\n<!-- Twitter用 -->\n<meta property="twitter:card" content="summary_large_image">\n<meta property="twitter:site" content="@netkeiba">\n<!-- Facebook用 -->\n<meta property="fb:admins" content="30367" />\n<!-- アノテーション -->\n<link rel="canonical" href="https://db.netkeiba.com/horse/2007110038/" />\n<link rel="alternate" media="only screen and (max-width: 640px)" href="https://db.sp.netkeiba.com/horse/2007110038/" />\n<link rel="alternate" href="https://db.netkeiba.com/horse/2007110038/"  hreflang="ja" />\n<link rel="alternate" href="https://db.netkeiba.com/horse/2007110038/"  hreflang="x-default" />\n<link rel="alternate" href="https://en.netkeiba.com/db/horse/2007110038/" hreflang="en" />\n<link rel="alternate" type="application/rss+xml" href="https://rss.netkeiba.com/?pid=rss_netkeiba&site=netkeiba" />\n<link rel="apple-touch-icon" href="https://cdn.netkeiba.com/img.sp/common/img/common/icon_home.png" />\n<title>クレバーロッシー (Clever Rossi) | 競走馬データ - netkeiba</title>\n\n\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/tab_change_jquer.js"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.select.js"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.MetaData.js"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/jquery.colorbox.js?20180321"></script>\n<script type="text/javascript" src="https://cdn.netkeiba.com/img.db/common/js/slick.js"></script>\n<link rel="stylesheet" href="https://cdn.netkeiba.com/img.db/common/css/colorbox.css?20180321" type="text/css" media="screen">\n<link rel="stylesheet" href="https://cdn.netkeiba.com/img.db/common/css/slick.css?20200928" type="text/css" media="screen">\n<link rel="stylesheet" href="https://cdn.netkeiba.com/img.db/common/css/paddock.css?20230601" type="text/css" media="all" />\n\n\n\n<script type="text/javascript">\nwindow._taboola = window._taboola || [];\n_taboola.push({article:\'auto\'});\n!function (e, f, u, i) {\nif (!document.getElementById(i)){\ne.async = 1;\ne.src = u;\ne.id = i;\nf.parentNode.insertBefore(e, f);\n}\n}(document.createElement(\'script\'),\ndocument.getElementsByTagName(\'script\')[0],\n\'//cdn.taboola.com/libtrc/netkeiba/loader.js\',\n\'tb_loader_script\');\nif(window.performance && typeof window.performance.mark == \'function\')\n{window.performance.mark(\'tbl_ic\');}\n</script>\n\n\n<!-- Google Tag Manager -->\n<script>\nwindow.dataLayer = window.dataLayer || [];\ndataLayer.push({\n\'itemInfo\': \'\',\'memberRank\': \'NotLogin\',\'memberId\': \'\'\n});\n</script>\n\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\'//www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-K6PJT6\');</script>\n<!-- End Google Tag Manager -->\n</head>\n<body class="db " id="horse_detail">\n<noscript>\nお客様のブラウザはジャバスクリプト（JavaScript）に対応していないか無効になっています。\n</noscript>\n<div id="page">\n\n<link rel="stylesheet" href="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/css/pc_header.css?20241225" type="text/css" media="screen" />\n<style>\n* {\nmargin: 0;\npadding: 0;\nfont-size: 100%;\n/*vertical-align: baseline;*/\ntext-shadow: none;\n-webkit-text-size-adjust: none !important;\noutline: none;\n}\nheader .Header_Inner {\nwidth: unset;\n}\nheader .Header_Inner .SiteToggleBtn01 a {\nmin-width: unset;\n}\n</style>\n<p class="sp_nk_btn disp_none"><a href="http://www.netkeiba.com/?pid=go_sp" title="スマートフォン版へ"><img src="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/image/sp_nk_link_02.png" alt="スマートフォン版へ" class="imgover" /></a></p>\n<header class="Header_Area fc">\n<div class="Header_Inner fc">\n<h1>\n<a href="https://www.netkeiba.com/?rf=logo" title="netkeiba">\n<img src="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/image/common/netkeiba_logo02.png?20231003" alt="netkeiba">\n</a>\n</h1>\n<div class="DB_Search_Input">\n<span id="gnavi_search_form">\n<img src="https://cdn.netkeiba.com/img.db/common/img/gif_loader.gif" />\n</span>\n<script>\n$(function(){\n$.get(\'https://db.netkeiba.com//ajax_gnavi_search.html\',{\ninput: \'UTF-8\',\noutput: \'json\',\n},function(data){\nif(\'OK\' == data.status){\n$(\'#gnavi_search_form\').html(data.data);\n}\n});\n});\n</script>\n</div><!-- / .DB_Search_Input -->\n<div class="MyMenuWrap">\n<ul class="UserMyMenu fc">\n\n<li>\n<a href="https://regist.netkeiba.com/?pid=premium&rf=header">\n<span>プレミアムサービス</span>\n</a>\n</li>\n<li>\n<a href="https://race.netkeiba.com/bookmark/bookmark.html?rf=navi" class="Icon_Header Icon_MyfavHorse">\n<span>お気に入り馬</span>\n</a>\n</li>\n<li>\n<a href="https://race.netkeiba.com/notes/schedule.html?rf=navi" class="Icon_Header Icon_Note">\n<span>メモ</span>\n</a>\n</li>\n<li>\n<a href="https://regist.netkeiba.com/account/?pid=login" class="Icon_Header Icon_Login">\n<span>ログイン/会員登録</span>\n</a>\n</li>\n<li class="disp_none header_stage_area no_login_show">\n<a href="https://regist.netkeiba.com/?pid=stage_login&action=login&return_url=https://regist.netkeiba.com/">\n<span>(s)ログイン</span>\n</a>\n</li>\n<li class="disp_none header_stage_area no_login_show">\n<a href="https://regist.netkeiba.com/?pid=user_add_form&payment=nk_user&goods_cd=310409&opt=init">\n<span>(s)無料会員登録</span>\n</a>\n<li class="disp_none header_stage_area login_show">\n<a href="https://regist.netkeiba.com/?pid=stage_login&action=logout&return_url=https://regist.netkeiba.com/">\n<span>(s)ログアウト</span>\n</a>\n</li>\n</ul>\n<div class="SiteToggleBtn01 Keirin">\n<a href="https://keirin.netkeiba.com/?rf=nk_pc_header">\n<span class="LiveRace">LIVE</span>\n<img src="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/image/common/icon_keirin01.png" alt="" width="21" height="16" class="KeirinLogoMark01">競輪\n</a>\n</div><!-- /.SiteToggleBtn01 -->\n</div>\n</div><!-- /.Header_Inner -->\n</header>\n<nav class="ContentNavi01">\n<ul class="fc">\n<li class="Top">\n<a href="https://www.netkeiba.com/?rf=navi" title="トップ" id="navi_link_top">トップ</a>\n</li>\n<li class="News">\n<a href="https://news.netkeiba.com/?rf=navi" title="ニュース" id="navi_link_news">ニュース</a>\n</li>\n<li class="Race">\n<a href="https://race.netkeiba.com/top/?rf=navi" title="レース" id="navi_link_race">レース</a>\n</li>\n<li class="AI New">\n<a href="https://race.netkeiba.com/AI/AI.html?rf=navi" title="AI" id="navi_link_AI">A I</a>\n</li>\n<!-- <li class="Special">\n<a href="https://race.netkeiba.com/special/index.html?id=0059&rf=navi" title="日本ダービー" id="navi_link_Special">日本ダービー</a>\n</li> -->\n<li class="Yoso">\n<a href="https://yoso.netkeiba.com/?access=init&rf=navi" title="予想" id="navi_link_yoso">予想</a>\n</li>\n<li class="Builder New">\n<a href="https://builder.netkeiba.com/?rf=navi" title="UMAIビルダー" id="navi_link_builder">UMAIビルダー</a>\n</li>\n<li class="Column">\n<a href="https://news.netkeiba.com/?pid=column_top&rf=navi" title="コラム" id="navi_link_column">コラム</a>\n</li>\n<li class="Tv">\n<a href="https://tv.netkeiba.com/?rf=navi" title="netkeibaTV" id="navi_link_tv">netkeibaTV</a>\n</li>\n<li class="Local">\n<a href="https://nar.netkeiba.com/top/?rf=navi" title="地方競馬" id="navi_link_nar">地方競馬</a>\n</li>\n<li class="Db">\n<a href="https://db.netkeiba.com/?rf=navi" title="データベース" id="navi_link_db">データベース</a>\n</li>\n<li class="Shop New">\n<a href="https://shop.netkeiba.com/?utm_source=netkeiba&utm_medium=+referral&utm_campaign=pcgnavi_20240425" title="ショップ" id="navi_link_shop" target="_blank">ショップ</a>\n</li>\n<li class="Paper">\n<a href="https://yoso.netkeiba.com/senmonshi/?rf=navi" title="競馬新聞" id="navi_link_senmonshi">競馬新聞</a>\n</li>\n<li class="YosoCS">\n<a href="https://orepro.netkeiba.com/?rf=navi" title="俺プロ" id="navi_link_orepro">俺プロ</a>\n</li>\n<li class="Owner">\n<a href="https://owner.netkeiba.com/?rf=navi" title="一口馬主" id="navi_link_owner">一口馬主</a>\n</li>\n<li class="Pog">\n<a href="https://pog.netkeiba.com/?rf=navi" title="POG" id="navi_link_pog">POG</a>\n</li>\n<li class="Matome">\n<a href="https://dir.netkeiba.com/keibamatome/index.html?rf=navi" title="まとめ" id="navi_link_keibamatome">まとめ</a>\n</li>\n</ul>\n</nav><!-- /.ContentNavi01 -->\n<!-- Geniee Wrapper Head Tag -->\n<script>\nwindow.gnshbrequest = window.gnshbrequest || {cmd:[]};\ngnshbrequest.cmd.push(function(){\ngnshbrequest.registerPassback("1491447");\ngnshbrequest.registerPassback("1491448");\ngnshbrequest.registerPassback("1492793");\ngnshbrequest.registerPassback("1491462_1");\ngnshbrequest.forceInternalRequest();\n});\n</script>\n<script async src="https://cpt.geniee.jp/hb/v1/211239/47/wrapper.min.js"></script>\n<!-- /Geniee Wrapper Head Tag -->\n<script async src="https://cdn.netkeiba.com/img.racev4.sp/common/js/nd_util.min.js"></script>\n<script type="text/javascript">\n$(document).ready(function() {\nshow_user();\n});\nfunction show_user(){\nvar is_stage = \'\';\nvar is_user  = \'\';\nvar is_alert = \'\';\nvar is_sp    = \'\';\nvar nickname = \'\';\nvar user_img = \'\';\nif(is_sp) {\n$(\'.sp_nk_btn\').show();\n}\nif(! is_stage) {\n$(\'.header_stage_area\').remove();\n}\nif(is_user){\n//ログイン中\n$(\'.login_show\').show();\nif(is_alert) {\n$(\'.Alert_New\').show();\n}\n} else {\n//未ログイン\n$(\'.no_login_show\').show();\n$(\'.login_show\').remove();\n}\n}\n</script>\n\n<div class="genre_menu fc">\n<ul>\n<li ><a href="https://db.netkeiba.com/" title="競馬データTOP">競馬データTOP</a></li>\n<li class=\'active\'><a href="https://db.netkeiba.com/horse/top.html" title="競走馬">競走馬</a></li>\n<li ><a href="https://db.netkeiba.com/jockey/top.html" title="騎手">騎手</a></li>\n<li ><a href="https://db.netkeiba.com/trainer/top.html" title="調教師">調教師</a></li>\n<li ><a href="https://db.netkeiba.com/owner/top.html" title="馬主">馬主</a></li>\n<li ><a href="https://db.netkeiba.com/breeder/top.html" title="生産者">生産者</a></li>\n<li ><a href="https://db.netkeiba.com/?pid=race_top" title="レース">レース</a></li>\n<li ><a href="https://db.netkeiba.com/?pid=classic_index" title="クラシック">クラシック</a></li>\n<li ><a href="https://db.sp.netkeiba.com/winner_search/home" title="勝ち馬サーチ">勝ち馬サーチ</a></li>\n</ul>\n</div><!-- /.genre_menu -->\n<div id="contents" class="fc">\n\n<style>\n.add_bnr{\nmargin:20px 0 10px;\ntext-align: center;\n}\n.add_bnr a{\ndisplay: inline-block;\n}\n</style>\n<div class="add_bnr">\n\n<div id="pc_nk_db_horse1st"></div>\n<script language="JavaScript" type="text/javascript">\n//noCacheParam=Math.random()*10000000000;document.write(\'<scr\'+\'ipt type="text/javascript" src="https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=pc_nk_db_horse1st&isJS=true&encoding=EUC-JP&ord=\' + noCacheParam + \'"></scr\'+\'ipt>\');\nif ($(\'#pc_nk_db_horse1st\').html().length<1){\n$.ajax(\'https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=pc_nk_db_horse1st\', {\ntimeout : 10000, /* 10000 ms */\n}).then(function(data) { $("#pc_nk_db_horse1st").html(data)} )\n}\n</script>\n</div>\n<div class="top_newinfo_box fc">\n<dl>\n<dd>\n<div style="line-height: 1.8em;">\n<a href="https://info.netkeiba.com/?pid=info_detail&id=1183" target="_blank" title="netkeirin"><img src="https://cdn.netkeiba.com/img.db/common/image/mark_arrow_red_01.gif" border="0" style="display:inline"><span style="text-indent:4px">コミュニティ健全化に向けた取り組みについて</span></a>\n</div>\n<div style="line-height: 1.8em;">\n<a href="//keirin.netkeiba.com/?rf=nk_pc_dbhorse" target="_blank" title="netkeirin"><img src="https://cdn.netkeiba.com/img.db/common/image/mark_arrow_blue_01.gif" border="0" style="display:inline"><span style="text-indent:4px">いま競輪が熱い！ netkeirinで競輪を気軽に楽しもう</span></a>\n</div>\n<div style="line-height: 1.8em;">\n<!-- <a href="//keirin.netkeiba.com/?rf=nk_pc_dbhorse" target="_blank" title="netkeirin"><img src="https://cdn.netkeiba.com/img.db/common/image/mark_arrow_blue_01.gif" border="0" style="display:inline"><span style="text-indent:4px">なぞのテキストリンク1</span></a> -->\n<!-- new_db_text1 ad start  -->\n<div id="new_db_text1"></div>\n<script language="JavaScript" type="text/javascript">\nif ($(\'#new_db_text1\').html().length<1){\n$.ajax(\'https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=new_db_text1\', {\ntimeout : 10000, /* 10000 ms */\n}).then(function(data) { $("#new_db_text1").html(data)} )\n}\n//noCacheParam=Math.random()*10000000000;\n//document.write(\'<scr\'+\'ipt type="text/javascript" src="https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=new_db_text1&isJS=true&encoding=EUC-JP&ord=\' + noCacheParam + \'"></scr\'+\'ipt>\');\n</script><!--noscript><iframe marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" bordercolor="#000000" width="700" height="20" src="https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=new_db_text1&encoding=EUC-JP"></iframe></noscript-->\n<!-- new_db_text1 ad end  -->\n</div>\n<div style="line-height: 1.8em;">\n<!-- <a href="//keirin.netkeiba.com/?rf=nk_pc_dbhorse" target="_blank" title="netkeirin"><img src="https://cdn.netkeiba.com/img.db/common/image/mark_arrow_blue_01.gif" border="0" style="display:inline"><span style="text-indent:4px">なぞのテキストリンク2</span></a> -->\n<!-- new_db_text2 ad start  -->\n<div id="new_db_text2"></div>\n<script language="JavaScript" type="text/javascript">\nif ($(\'#new_db_text2\').html().length<1){\n$.ajax(\'https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=new_db_text2\', {\ntimeout : 10000, /* 10000 ms */\n}).then(function(data) { $("#new_db_text2").html(data)} )\n}\n//noCacheParam=Math.random()*10000000000;\n//document.write(\'<scr\'+\'ipt type="text/javascript" src="https://netdreamersad.durasite.net/A-affiliate2/mobile?site=23&keyword=new_db_text2&isJS=true&encoding=EUC-JP&ord=\' + noCacheParam + \'"></scr\'+\'ipt>\');\n</script><noscript><iframe marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" bordercolor="#000000" width="700" height="20" src="https://net

In [30]:
contents = pd.read_html(html.text)

C:\Users\cyank\AppData\Local\Temp\ipykernel_26204\533704518.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  contents = pd.read_html(html.text)

In [31]:
contents[1]

IndexError: list index out of range

# スクレイピングのコードの動作確認

In [1]:
import my_snipets
import random
import requests
from io import StringIO

import pandas as pd

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

In [ ]:
horseID = "2002100816"

service = Service()
service.creation_flags = 0x08000000  
option = Options()
#option.add_argument('--headless')

browser = webdriver.Chrome(options=option,service=service)
browser.get("https://db.netkeiba.com/horse/" + horseID)

page_source = browser.page_source

browser.get("https://db.netkeiba.com/horse/ped/" + horseID)
page_source2 = browser.page_source
browser.quit()

with open(f"../../../data/html/horse/{horseID}.txt","w",encoding="utf-8") as f:
    f.write(page_source)

In [56]:
with open(f"../../../data/html/horse/{horseID}.txt","r",encoding="utf-8") as f:
    html = f.read()

In [61]:
pd.read_html(StringIO(html))[4]

,日付,開催,天 気,R,レース名,映 像,頭 数,枠 番,馬 番,オ ッ ズ,...,着差,ﾀｲﾑ 指数,通過,ペース,上り,馬体重,厩舎 ｺﾒﾝﾄ,備考,勝ち馬 (2着馬),賞金
0,2006/12/24,5中山8,晴,9,有馬記念(GI),NaN,14,3.0,4,1.2,...,-0.5,**,12-12-11-10,30.0-35.4,33.8,438(+2),NaN,NaN,(ポップロック),18302.4
1,2006/11/26,5東京8,小雨,10,ジャパンC(GI),NaN,11,6.0,6,1.3,...,-0.3,**,11-11-11-7,37.0-34.3,33.5,436(0),NaN,NaN,(ドリームパスポート),25235.2
2,2006/10/01,フランス,晴,7,凱旋門賞(GI),NaN,8,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,計不,NaN,NaN,RAIL LINK,NaN
3,2006/06/25,4京都4,雨,11,宝塚記念(GI),NaN,13,6.0,8,1.1,...,-0.7,**,12-12-9-7,36.2-35.8,34.9,442(+4),NaN,NaN,(ナリタセンチュリー),13473.0
4,2006/04/30,3京都4,晴,11,天皇賞(春)(GI),NaN,17,4.0,7,1.1,...,-0.6,**,14-14-4-1,36.2-33.5,33.5,438(-4),NaN,NaN,(リンカーン),13573.8
5,2006/03/19,1阪神8,曇,11,阪神大賞典(GII),NaN,9,2.0,2,1.1,...,-0.6,**,6-6-4-2,36.8-37.5,36.8,442(+2),NaN,NaN,(トウカイトリック),6564.4
6,2005/12/25,5中山8,晴,9,有馬記念(GI),NaN,16,3.0,6,1.3,...,0.1,**,11-10-8-6,30.1-35.5,34.6,440(-4),NaN,NaN,ハーツクライ,7296.0
7,2005/10/23,4京都6,晴,11,菊花賞(GI),NaN,16,4.0,7,1.0,...,-0.3,NaN,7-7-7-7,36.3-35.7,33.3,444(-4),NaN,NaN,(アドマイヤジャパン),15246.7
8,2005/09/25,4阪神6,曇,11,神戸新聞杯(GII),NaN,13,6.0,9,1.1,...,-0.4,NaN,12-12-11-5,35.1-35.0,34.1,448(0),NaN,NaN,(シックスセンス),5495.2
9,2005/05/29,3東京4,晴,10,東京優駿(GI),NaN,18,3.0,5,1.1,...,-0.8,NaN,15-13-12-10,35.5-34.5,33.4,448(+4),NaN,NaN,(インティライミ),18975.3
10,2005/04/17,3中山8,晴,11,皐月賞(GI),NaN,18,7.0,14,1.3,...,-0.4,NaN,15-16-9-9,35.0-34.5,34.0,444(-2),NaN,NaN,(シックスセンス),13200.0
11,2005/03/06,2中山4,曇,11,報知杯弥生賞(GII),NaN,10,8.0,10,1.2,...,0.0,NaN,8-7-7-3,37.4-34.9,34.1,446(-4),NaN,NaN,(アドマイヤジャパン),5475.6
12,2005/01/22,1京都7,曇,10,若駒S(OP),NaN,7,4.0,4,1.1,...,-0.9,NaN,7-7-6-6,35.0-36.1,33.6,450(-2),NaN,NaN,(ケイアイヘネシー),1917.5
13,2004/12/19,5阪神6,晴,5,2歳新馬,NaN,9,4.0,4,1.1,...,-0.7,NaN,4-5-3-3,39.5-33.4,33.1,452(0),NaN,NaN,(コンゴウリキシオー),700.0

In [2]:
from makeRawData import makeRaceData,makeHorseData

from bs4 import BeautifulSoup

In [4]:
MRD = makeRaceData("202501","202501")
MRD.makeYMList()
MRD.makeRaceDateURLList()
MRD.makeRaceURLList()
MRD.screpingRaceHTML(skip=True)
MRD.makeRawDataRace(skip=True)

2025/01～2025/01のレース情報のデータを作成します。

makeYMList: 100%|██████████| 1/1 [00:00<00:00, 664.08it/s]
makeRaceDateURLList: 100%|██████████| 1/1 [00:02<00:00,  2.13s/it]
makeRaceURLList: 100%|██████████| 9/9 [00:14<00:00,  1.61s/it, date=2025/01/26]
screpingRaceHTML: 100%|██████████| 240/240 [09:04<00:00,  2.27s/it, raceID=202510010212]
makeRawDataRace: 100%|██████████| 240/240 [00:59<00:00,  4.04it/s, raceID=202510010212]

2025/01～2025/01のレース情報のデータを作成しました

In [5]:
df = pd.read_pickle("../../../data/rawData/raceResults/202506010101.pickle")

In [8]:
horseIDList = df["horseID"].tolist()

In [9]:
MHD = makeHorseData(horseIDList)
MHD.getHorseHTML(skipResult=True, skipPED=True)

16頭の馬の過去成績/血統表データを作成します。

getHorseHTML: 100%|██████████| 16/16 [00:40<00:00,  2.52s/it, horseID=2022103312(血統表)]

In [ ]:
MHD.makeHorseRawData(skipResult=True, skipPED=True)

In [10]:
horseID = horseIDList[0]

In [11]:
with open(f"../../../data/html/horse/{horseID}.txt","r",encoding="utf-8") as f:
    html = f.read()

#htmlから過去戦績のデータを抽出
contents = pd.read_html(StringIO(html))
if len(contents) < 3 :
    horseResults = pd.DataFrame(columns=my_snipets.getHorseResultsColumns())
elif contents[2].columns[0] == "日付":
    horseResults = contents[2]
else:
    horseResults = contents[3]

In [12]:
horseResults

,日付,開催,天 気,R,レース名,映 像,頭 数,枠 番,馬 番,オ ッ ズ,...,着差,ﾀｲﾑ 指数,通過,ペース,上り,馬体重,厩舎 ｺﾒﾝﾄ,備考,勝ち馬 (2着馬),賞金
0,2025/08/25,川崎,晴,10,凌霄花特別(B3),NaN,13,5,7,15.2,...,3.4,**,5-6-11-12,30.7-40.1,42.4,462(0),NaN,NaN,ビップソリオ,NaN
1,2025/07/10,川崎,晴,8,バカラ賞(C1二),NaN,12,1,1,2.5,...,-0.4,**,1-1-1-1,38.9-40.3,40.3,462(+4),NaN,NaN,(エーステンペスト),180.0
2,2025/05/17,2東京7,雨,7,3歳1勝クラス,NaN,14,4,5,37.6,...,4.8,**,5-8,34.2-36.3,39.9,458(+4),NaN,NaN,ベンヌ,NaN
3,2025/03/09,2中山4,晴,6,3歳1勝クラス,NaN,15,4,7,7.6,...,0.9,**,11-11,33.4-37.1,37.1,454(-6),NaN,NaN,マサノユニコーン,NaN
4,2025/01/05,1中山1,晴,1,3歳未勝利,NaN,16,6,11,2.5,...,-0.5,**,1-1,34.5-37.7,37.7,460(+2),NaN,NaN,(グリューネベルグ),560.0
5,2024/12/15,5中山6,晴,6,2歳新馬,NaN,16,7,14,13.0,...,0.1,**,5-6,34.8-38.3,37.6,458(0),NaN,NaN,サヨノジャンボリー,290.0

In [14]:
import re

In [16]:
columns = ["F","FF","FFF","FFFF","FFFFF","FFFFM","FFFM","FFFMF","FFFMM","FFM","FFMF","FFMFF","FFMFM","FFMM","FFMMF","FFMMM","FM","FMF","FMFF","FMFFF","FMFFM","FMFM","FMFMF","FMFMM","FMM","FMMF","FMMFF","FMMFM","FMMM","FMMMF","FMMMM",
            "M","MF","MFF","MFFF","MFFFF","MFFFM","MFFM","MFFMF","MFFMM","MFM","MFMF","MFMFF","MFMFM","MFMM","MFMMF","MFMMM","MM","MMF","MMFF","MMFFF","MMFFM","MMFM","MMFMF","MMFMM","MMM","MMMF","MMMFF","MMMFM","MMMM","MMMMF","MMMMM"]

In [32]:
with open(f"../../../data/html/ped/{horseID}.txt","r",encoding="utf-8") as f: #ファイルを開く
    html = f.read()       

soup = BeautifulSoup(html,"html.parser") #htmlをsoupオブジェクトへ

contents = soup.find("table",attrs={"summary":"5代血統表"}).find_all("a",attrs={"href":re.compile(r"/horse/\d+")}) #血統表の馬名の部分を抽出

pedHorseNameList = []
for text in contents:
    text2 = str(text.text)
    text3 = text2.split("\n")[0]
    pedHorseNameList.append(text3)

PEDFinDF = pd.DataFrame(pedHorseNameList).T
for i in range(len(columns)):
    PEDFinDF.rename(columns={int(f"{i}"):f"{columns[i]}"},inplace=True)
PEDFinDF.rename(index={0:str(horseID)},inplace=True)

In [33]:
PEDFinDF

,F,FF,FFF,FFFF,FFFFF,FFFFM,FFFM,FFFMF,FFFMM,FFM,...,MMFM,MMFMF,MMFMM,MMM,MMMF,MMMFF,MMMFM,MMMM,MMMMF,MMMMM
2022105247,マジェスティックウォリアー,A.P. Indy,Seattle Slew,Bold Reasoning,Boldnesian,Reason to Earn,My Charmer,Poker,Fair Charmer,Weekend Surprise,...,ニホンピロエバート,チャイナロック,ライトフレーム,ドッフ,Mr. Prospector,Raise a Native,Gold Digger,Furling,Hoist the Flag,Continue

In [34]:
horseID

'2022105247'

In [31]:
soup.find("table",attrs={"summary":"5代血統表"}).find_all("a",attrs={"href":re.compile(r"/horse/\d+")})

[<a href="https://db.netkeiba.com/horse/000a011e9c/">マジェスティックウォリアー

 		<br/>Majestic Warrior(米)

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a001d37/">A.P. Indy

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a0015fc/">Seattle Slew

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a001598/">Bold Reasoning</a>,
 <a href="https://db.netkeiba.com/horse/000a001599/">Boldnesian</a>,
 <a href="https://db.netkeiba.com/horse/000a007e08/">Reason to Earn</a>,
 <a href="https://db.netkeiba.com/horse/000a008080/">My Charmer</a>,
 <a href="https://db.netkeiba.com/horse/000a00110c/">Poker</a>,
 <a href="https://db.netkeiba.com/horse/000a008081/">Fair Charmer</a>,
 <a href="https://db.netkeiba.com/horse/000a009821/">Weekend Surprise

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a000ded/"><span class="red">Secretariat</span></a>,
 <a href="https://db.netkeiba.com/horse/000a000e94/">Bold Ruler</a>,
 <a href="https://db.netkeiba.com/horse/000a007a74/">Somethingroyal</a>,
 <a href="https://db.netkeiba.com/horse/000a009820/">Lassie Dear</a>,
 <a href="https://db.netkeiba.com/horse/000a000e0e/"><span class="red">Buckpasser</span></a>,
 <a href="https://db.netkeiba.com/horse/000a008098/">Gay Missile</a>,
 <a href="https://db.netkeiba.com/horse/000a011eae/">Dream Supreme

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a001bea/">Seeking the Gold

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a001607/"><span class="red">Mr. Prospector</span></a>,
 <a href="https://db.netkeiba.com/horse/000a000e46/">Raise a Native</a>,
 <a href="https://db.netkeiba.com/horse/000a007e0c/">Gold Digger</a>,
 <a href="https://db.netkeiba.com/horse/000a0087a5/">Con Game</a>,
 <a href="https://db.netkeiba.com/horse/000a000e0e/"><span class="red">Buckpasser</span></a>,
 <a href="https://db.netkeiba.com/horse/000a007c3b/">Broadway</a>,
 <a href="https://db.netkeiba.com/horse/000a011ead/">Spinning Round

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a0017b2/">Dixieland Band</a>,
 <a href="https://db.netkeiba.com/horse/000a000e04/">Northern Dancer</a>,
 <a href="https://db.netkeiba.com/horse/000a0085d7/">Mississippi Mud</a>,
 <a href="https://db.netkeiba.com/horse/000a0114e1/">Take Heart</a>,
 <a href="https://db.netkeiba.com/horse/000a000ded/"><span class="red">Secretariat</span></a>,
 <a href="https://db.netkeiba.com/horse/000a011199/">Deck Stewardess</a>,
 <a href="https://db.netkeiba.com/horse/2007102719/">エアティアーモ

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a010a10/">ロージズインメイ

 		    <br/>Roses in May(米)

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a002109/">Devil His Due

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a001a8f/">Devil's Bag</a>,
 <a href="https://db.netkeiba.com/horse/000a0012bf/">Halo</a>,
 <a href="https://db.netkeiba.com/horse/000a0085ed/">Ballade</a>,
 <a href="https://db.netkeiba.com/horse/000a009f28/">Plenty O'Toole</a>,
 <a href="https://db.netkeiba.com/horse/000a001787/">Raise a Cup</a>,
 <a href="https://db.netkeiba.com/horse/000a009f27/">Li'l Puss</a>,
 <a href="https://db.netkeiba.com/horse/000a00b187/">Tell a Secret

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a00180b/">Speak John</a>,
 <a href="https://db.netkeiba.com/horse/000a000fc7/">Prince John</a>,
 <a href="https://db.netkeiba.com/horse/000a008739/">Nuit de Folies</a>,
 <a href="https://db.netkeiba.com/horse/000a00a6a7/">Secret Retreat</a>,
 <a href="https://db.netkeiba.com/horse/000a001981/">Clandestine</a>,
 <a href="https://db.netkeiba.com/horse/000a00a6a6/">Retirement</a>,
 <a href="https://db.netkeiba.com/horse/1999106803/">エアコゼット

 		</a>,
 <a href="https://db.netkeiba.com/horse/1980106362/">ニホンピロウイナー

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a0004ce/">スティールハート</a>,
 <a href="https://db.netkeiba.com/horse/000a000f2a/">Habitat</a>,
 <a href="https://db.netkeiba.com/horse/000a007c1d/">A. 1.</a>,
 <a href="https://db.netkeiba.com/horse/1955105079/">ニホンピロエバート</a>,
 <a href="https://db.netkeiba.com/horse/000a0009ab/">チャイナロック</a>,
 <a href="https://db.netkeiba.com/horse/1959100614/">ライトフレーム</a>,
 <a href="https://db.netkeiba.com/horse/000a0000f7/">ドッフ

 		    <br/>Doff(米)

 		</a>,
 <a href="https://db.netkeiba.com/horse/000a001607/"><span class="red">Mr. Prospector</span></a>,
 <a href="https://db.netkeiba.com/horse/000a000e46/">Raise a Native</a>,
 <a href="https://db.netkeiba.com/horse/000a007e0c/">Gold Digger</a>,
 <a href="https://db.netkeiba.com/horse/000a0091a3/">Furling</a>,
 <a href="https://db.netkeiba.com/horse/000a0012be/">Hoist the Flag</a>,
 <a href="https://db.netkeiba.com/horse/000a000595/">Continue</a>]

In [20]:
soup

<html id="html" lang="ja" xml:lang="ja" xmlns="http://www.w3.org/1999/xhtml"><head><style type="text/css">.swal-icon--error{border-color:#f27474;-webkit-animation:animateErrorIcon .5s;animation:animateErrorIcon .5s}.swal-icon--error__x-mark{position:relative;display:block;-webkit-animation:animateXMark .5s;animation:animateXMark .5s}.swal-icon--error__line{position:absolute;height:5px;width:47px;background-color:#f27474;display:block;top:37px;border-radius:2px}.swal-icon--error__line--left{-webkit-transform:rotate(45deg);transform:rotate(45deg);left:17px}.swal-icon--error__line--right{-webkit-transform:rotate(-45deg);transform:rotate(-45deg);right:16px}@-webkit-keyframes animateErrorIcon{0%{-webkit-transform:rotateX(100deg);transform:rotateX(100deg);opacity:0}to{-webkit-transform:rotateX(0deg);transform:rotateX(0deg);opacity:1}}@keyframes animateErrorIcon{0%{-webkit-transform:rotateX(100deg);transform:rotateX(100deg);opacity:0}to{-webkit-transform:rotateX(0deg);transform:rotateX(0deg);opacity:1}}@-webkit-keyframes animateXMark{0%{-webkit-transform:scale(.4);transform:scale(.4);margin-top:26px;opacity:0}50%{-webkit-transform:scale(.4);transform:scale(.4);margin-top:26px;opacity:0}80%{-webkit-transform:scale(1.15);transform:scale(1.15);margin-top:-6px}to{-webkit-transform:scale(1);transform:scale(1);margin-top:0;opacity:1}}@keyframes animateXMark{0%{-webkit-transform:scale(.4);transform:scale(.4);margin-top:26px;opacity:0}50%{-webkit-transform:scale(.4);transform:scale(.4);margin-top:26px;opacity:0}80%{-webkit-transform:scale(1.15);transform:scale(1.15);margin-top:-6px}to{-webkit-transform:scale(1);transform:scale(1);margin-top:0;opacity:1}}.swal-icon--warning{border-color:#f8bb86;-webkit-animation:pulseWarning .75s infinite alternate;animation:pulseWarning .75s infinite alternate}.swal-icon--warning__body{width:5px;height:47px;top:10px;border-radius:2px;margin-left:-2px}.swal-icon--warning__body,.swal-icon--warning__dot{position:absolute;left:50%;background-color:#f8bb86}.swal-icon--warning__dot{width:7px;height:7px;border-radius:50%;margin-left:-4px;bottom:-11px}@-webkit-keyframes pulseWarning{0%{border-color:#f8d486}to{border-color:#f8bb86}}@keyframes pulseWarning{0%{border-color:#f8d486}to{border-color:#f8bb86}}.swal-icon--success{border-color:#a5dc86}.swal-icon--success:after,.swal-icon--success:before{content:"";border-radius:50%;position:absolute;width:60px;height:120px;background:#fff;-webkit-transform:rotate(45deg);transform:rotate(45deg)}.swal-icon--success:before{border-radius:120px 0 0 120px;top:-7px;left:-33px;-webkit-transform:rotate(-45deg);transform:rotate(-45deg);-webkit-transform-origin:60px 60px;transform-origin:60px 60px}.swal-icon--success:after{border-radius:0 120px 120px 0;top:-11px;left:30px;-webkit-transform:rotate(-45deg);transform:rotate(-45deg);-webkit-transform-origin:0 60px;transform-origin:0 60px;-webkit-animation:rotatePlaceholder 4.25s ease-in;animation:rotatePlaceholder 4.25s ease-in}.swal-icon--success__ring{width:80px;height:80px;border:4px solid hsla(98,55%,69%,.2);border-radius:50%;box-sizing:content-box;position:absolute;left:-4px;top:-4px;z-index:2}.swal-icon--success__hide-corners{width:5px;height:90px;background-color:#fff;padding:1px;position:absolute;left:28px;top:8px;z-index:1;-webkit-transform:rotate(-45deg);transform:rotate(-45deg)}.swal-icon--success__line{height:5px;background-color:#a5dc86;display:block;border-radius:2px;position:absolute;z-index:2}.swal-icon--success__line--tip{width:25px;left:14px;top:46px;-webkit-transform:rotate(45deg);transform:rotate(45deg);-webkit-animation:animateSuccessTip .75s;animation:animateSuccessTip .75s}.swal-icon--success__line--long{width:47px;right:8px;top:38px;-webkit-transform:rotate(-45deg);transform:rotate(-45deg);-webkit-animation:animateSuccessLong .75s;animation:animateSuccessLong .75s}@-webkit-keyframes rotatePlaceholder{0%{-webkit-transform:rotate(-45deg);transform:rotate(-45deg)}5%{-webkit-transform:rotate(-45deg);transform:rotate(-45deg)}12%{-webkit-transform:rotate(-405deg);transform:rotate(-405deg)}to{-webkit-transform:rotate(-405deg);transform:rotate(-405deg)}}@keyframes rotatePlaceholder{0%{-webkit-transform:rotate(-45deg);transform:rotate(-45deg)}5%{-webkit-transform:rotate(-45deg);transform:rotate(-45deg)}12%{-webkit-transform:rotate(-405deg);transform:rotate(-405deg)}to{-webkit-transform:rotate(-405deg);transform:rotate(-405deg)}}@-webkit-keyframes animateSuccessTip{0%{width:0;left:1px;top:19px}54%{width:0;left:1px;top:19px}70%{width:50px;left:-8px;top:37px}84%{width:17px;left:21px;top:48px}to{width:25px;left:14px;top:45px}}@keyframes animateSuccessTip{0%{width:0;left:1px;top:19px}54%{width:0;left:1px;top:19px}70%{width:50px;left:-8px;top:37px}84%{width:17px;left:21px;top:48px}to{width:25px;left:14px;top:45px}}@-webkit-keyframes animateSuccessLong{0%{width:0;right:46px;top:54px}65%{width:0;right:46px;top:54px}84%{width:55px;right:0;top:35px}to{width:47px;right:8px;top:38px}}@keyframes animateSuccessLong{0%{width:0;right:46px;top:54px}65%{width:0;right:46px;top:54px}84%{width:55px;right:0;top:35px}to{width:47px;right:8px;top:38px}}.swal-icon--info{border-color:#c9dae1}.swal-icon--info:before{width:5px;height:29px;bottom:17px;border-radius:2px;margin-left:-2px}.swal-icon--info:after,.swal-icon--info:before{content:"";position:absolute;left:50%;background-color:#c9dae1}.swal-icon--info:after{width:7px;height:7px;border-radius:50%;margin-left:-3px;top:19px}.swal-icon{width:80px;height:80px;border-width:4px;border-style:solid;border-radius:50%;padding:0;position:relative;box-sizing:content-box;margin:20px auto}.swal-icon:first-child{margin-top:32px}.swal-icon--custom{width:auto;height:auto;max-width:100%;border:none;border-radius:0}.swal-icon img{max-width:100%;max-height:100%}.swal-title{color:rgba(0,0,0,.65);font-weight:600;text-transform:none;position:relative;display:block;padding:13px 16px;font-size:27px;line-height:normal;text-align:center;margin-bottom:0}.swal-title:first-child{margin-top:26px}.swal-title:not(:first-child){padding-bottom:0}.swal-title:not(:last-child){margin-bottom:13px}.swal-text{font-size:16px;position:relative;float:none;line-height:normal;vertical-align:top;text-align:left;display:inline-block;margin:0;padding:0 10px;font-weight:400;color:rgba(0,0,0,.64);max-width:calc(100% - 20px);overflow-wrap:break-word;box-sizing:border-box}.swal-text:first-child{margin-top:45px}.swal-text:last-child{margin-bottom:45px}.swal-footer{text-align:right;padding-top:13px;margin-top:13px;padding:13px 16px;border-radius:inherit;border-top-left-radius:0;border-top-right-radius:0}.swal-button-container{margin:5px;display:inline-block;position:relative}.swal-button{background-color:#7cd1f9;color:#fff;border:none;box-shadow:none;border-radius:5px;font-weight:600;font-size:14px;padding:10px 24px;margin:0;cursor:pointer}.swal-button:not([disabled]):hover{background-color:#78cbf2}.swal-button:active{background-color:#70bce0}.swal-button:focus{outline:none;box-shadow:0 0 0 1px #fff,0 0 0 3px rgba(43,114,165,.29)}.swal-button[disabled]{opacity:.5;cursor:default}.swal-button::-moz-focus-inner{border:0}.swal-button--cancel{color:#555;background-color:#efefef}.swal-button--cancel:not([disabled]):hover{background-color:#e8e8e8}.swal-button--cancel:active{background-color:#d7d7d7}.swal-button--cancel:focus{box-shadow:0 0 0 1px #fff,0 0 0 3px rgba(116,136,150,.29)}.swal-button--danger{background-color:#e64942}.swal-button--danger:not([disabled]):hover{background-color:#df4740}.swal-button--danger:active{background-color:#cf423b}.swal-button--danger:focus{box-shadow:0 0 0 1px #fff,0 0 0 3px rgba(165,43,43,.29)}.swal-content{padding:0 20px;margin-top:20px;font-size:medium}.swal-content:last-child{margin-bottom:20px}.swal-content__input,.swal-content__textarea{-webkit-appearance:none;background-color:#fff;border:none;font-size:14px;display:block;box-sizing:border-box;width:100%;border:1px solid rgba(0,0,0,.14);padding:10px 13px;border-radius:2px;transition:border-color .2s}.swal-content__input:focus,.swal-content__textarea:focus{outline:none;border-color:#6db8ff}.swal-content__textarea{resize:vertical}.swal-button--loading{color:transparent}.swal-button--loading~.swal-button__loader{opacity:1}.swal-button__loader{position:absolute;height:auto;width:43px;z-index:2;left:50%;top:50%;-webkit-transform:translateX(-50%) translateY(-50%);transform:translateX(-50%) translateY(-50%);text-align:center;pointer-events:none;opacity:0}.swal-button__loader div{display:inline-block;float:none;vertical-align:baseline;width:9px;height:9px;padding:0;border:none;margin:2px;opacity:.4;border-radius:7px;background-color:hsla(0,0%,100%,.9);transition:background .2s;-webkit-animation:swal-loading-anim 1s infinite;animation:swal-loading-anim 1s infinite}.swal-button__loader div:nth-child(3n+2){-webkit-animation-delay:.15s;animation-delay:.15s}.swal-button__loader div:nth-child(3n+3){-webkit-animation-delay:.3s;animation-delay:.3s}@-webkit-keyframes swal-loading-anim{0%{opacity:.4}20%{opacity:.4}50%{opacity:1}to{opacity:.4}}@keyframes swal-loading-anim{0%{opacity:.4}20%{opacity:.4}50%{opacity:1}to{opacity:.4}}.swal-overlay{position:fixed;top:0;bottom:0;left:0;right:0;text-align:center;font-size:0;overflow-y:auto;background-color:rgba(0,0,0,.4);z-index:10000;pointer-events:none;opacity:0;transition:opacity .3s}.swal-overlay:before{content:" ";display:inline-block;vertical-align:middle;height:100%}.swal-overlay--show-modal{opacity:1;pointer-events:auto}.swal-overlay--show-modal .swal-modal{opacity:1;pointer-events:auto;box-sizing:border-box;-webkit-animation:showSweetAlert .3s;animation:showSweetAlert .3s;will-change:transform}.swal-modal{width:478px;opacity:0;pointer-events:none;background-color:#fff;text-align:center;border-radius:5px;position:static;margin:20px auto;display:inline-block;vertical-align:middle;-webkit-transform:scale(1);transform:scale(1);-webkit-transform-origin:50% 50%;transform-origin:50% 50%;z-index:10001;transition:opacity .2s,-webkit-transform .3s;transition:transform .3s,opacity .2s;transition:transform .3s,opacity .2s,-webkit-transform .3s}@media (max-width:500px){.swal-modal{width:calc(100% - 20px)}}@-webkit-keyframes showSweetAlert{0%{-webkit-transform:scale(1);transform:scale(1)}1%{-webkit-transform:scale(.5);transform:scale(.5)}45%{-webkit-transform:scale(1.05);transform:scale(1.05)}80%{-webkit-transform:scale(.95);transform:scale(.95)}to{-webkit-transform:scale(1);transform:scale(1)}}@keyframes showSweetAlert{0%{-webkit-transform:scale(1);transform:scale(1)}1%{-webkit-transform:scale(.5);transform:scale(.5)}45%{-webkit-transform:scale(1.05);transform:scale(1.05)}80%{-webkit-transform:scale(.95);transform:scale(.95)}to{-webkit-transform:scale(1);transform:scale(1)}}</style>
<!-- block=meta_tag_basic (d) -->
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="text/javascript" http-equiv="content-script-type"/>
<meta content="text/css" http-equiv="content-style-type"/>
<link href="https://cdn.netkeiba.com/img.db/common/css/reset.css?20160421" media="all" rel="stylesheet" type="text/css"/>
<link href="https://cdn.netkeiba.com/img.db/common/css/common.css?20210819" media="all" rel="stylesheet" type="text/css"/>
<link href="https://cdn.netkeiba.com/img.db/common/css/db_detail.css?20180621" media="all" rel="stylesheet" type="text/css"/>
<link href="https://cdn.netkeiba.com/img.db/common/css/horse_detail.css?20250620" media="all" rel="stylesheet" type="text/css"/>
<link href="https://cdn.netkeiba.com/img.db/common/css/win.css?20160421" media="all" rel="stylesheet" type="text/css"/>
<link href="https://cdn.netkeiba.com/img.db/common/css/db_top.css?20160421" media="all" rel="stylesheet" type="text/css"/>
<link href="https://cdn.netkeiba.com/img.db/common/css/prettyPhoto.css?20160421" rel="stylesheet" type="text/css"/>
<link href="https://cdn.netkeiba.com/img.db/common/css/jquery.fancybox-1.3.4.css?20160421" rel="stylesheet" type="text/css"/>
<link href="https://cdn.netkeiba.com/img.db/common/css/db_classic_nk01.css?201911209" rel="stylesheet" type="text/css"/>
<!-- link rel="stylesheet" href="https://cdn.netkeiba.com/img.www/style/netkeiba.ja/css/common_header.css" type="text/css" -->
<script async="" src="https://scripts.clarity.ms/0.8.27/clarity.js"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-BQDXGQBP6X&amp;cx=c&amp;gtm=4e58t1h1" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-B2L5N4JT6V&amp;cx=c&amp;gtm=4e58t1h1" type="text/javascript"></script><script async="" src="https://www.clarity.ms/tag/dfos4lrrd0"></script><script async="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="//www.googletagmanager.com/gtm.js?id=GTM-K6PJT6"></script><script language="javascript">
<!--
b = navigator.userAgent.toUpperCase();
if(b.indexOf("MAC") >= 0)
{
cssFile = "mac.css";
}
else
{
cssFile = "win.css";
}
document.write("<link rel='stylesheet' type='text/css' href='https://cdn.netkeiba.com/img.db/common/css/" + cssFile + "'>");
// -->
</script><link href="https://cdn.netkeiba.com/img.db/common/css/win.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.netkeiba.com/img.db/common/js/jquery-1.8.2.min.js?20160421" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.db/common/js/jquery.cookie.js?20160421" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.db/common/js/fontsize.js?20160421" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.db/common/js/jquery.prettyPhoto.js?20160421" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.db/common/js/jquery.fieldtag.js?20160421" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.db/common/js/table_hover.js?20160421" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.db/common/js/jquery.fancybox-1.3.4.pack.js?20160421" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.db/common/js/jquery.easing-1.3.pack.js?20160421" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.db/common/js/jquery.carouFredSel-6.2.0-packed.js?20160421" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.db/common/js/jquery.touchSwipe.min.js?20160421" type="text/javascript"></script>
<link href="https://cdn.netkeiba.com/img.db/common/css/ajaxtabs.css?20160421" rel="stylesheet" type="text/css"/>
<script src="https://cdn.netkeiba.com/img.db/common/js/ajaxtabs.js?20160421" type="text/javascript">
/***********************************************
* Ajax Tabs Content script v2.2- c Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/
</script>
<script src="https://cdn.netkeiba.com/img.db/common/js/get_ad_request.js" type="text/javascript"></script>
<script type="text/javascript">
<!--
var _user_action_api_url    = 'https://cdn.netkeiba.com/img.user';
var _newsapi_action_api_url = 'https://cdn.netkeiba.com/img.newsapi/';
var _social_action_api_url  = 'https://cdn.netkeiba.com/img.db/';
var _bbs_action_api_url     = 'https://bbs.netkeiba.com/';
// -->
</script>
<script src="https://cdn.netkeiba.com/img.user/common/js/user.action.js?2016042101" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.newsapi//common/js/newsapi.action.js?2016042101" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.db//common/js/social.action.js" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.bbs/common/js/bbs.action.js?2018053101" type="text/javascript"></script>
<script src="https://cdn.netkeiba.com/img.regist.sp//common/js/monthly_goods_link.js?2017080201" type="text/javascript"></script>
<!-- block=meta_tag_db_horse_subdir (d) -->
<title>ピッツァナポリ (Pizza Napoli) | 競走馬データ - netkeiba</title>
<meta content="ja" http-equiv="content-language"/>
<meta content="width=device-960px" name="viewport"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="ピッツァナポリ (Pizza Napoli)の競走馬データです。競走成績、血統情報、産駒情報などをはじめ、50万頭以上の競走馬・騎手・調教師・馬主・生産者・レースの全データがご覧いただけます。" name="description"/>
<meta content="競馬情報,競走馬,騎手,レース,調教師,馬主,検索,データベース,JRA,netkeiba,ネット競馬" name="keywords"/>
<meta content="" name="thumbnail"/>
<!-- ogp用 -->
<meta content="netkeiba" property="og:site_name"/>
<meta content="article" property="og:type"/>
<meta content="ピッツァナポリ (Pizza Napoli) | 競走馬データ - netkeiba" property="og:title"/>
<meta content="https://db.netkeiba.com//horse/2022105247/" property="og:url"/>
<meta content="ピッツァナポリ (Pizza Napoli)の競走馬データです。競走成績、血統情報、産駒情報などをはじめ、50万頭以上の競走馬、騎手・調教師・馬主・生産者の全データがご覧いただけます。" property="og:description"/>
<meta content="__GLOBAL_CDN_DB_show_photo.php?horse_id=2022105247&amp;no=ランダムに抽出 ToDo&amp;tn=yes" property="og:image"/>
<!-- Twitter用 -->
<meta content="summary_large_image" property="twitter:card"/>
<meta content="@netkeiba" property="twitter:site"/>
<!-- Facebook用 -->
<meta content="30367" property="fb:admins"/>
<!-- アノテーション -->
<link href="https://db.netkeiba.com/horse/2022105247/" rel="canonical"/>
<link href="https://db.sp.netkeiba.com/horse/2022105247/" media="only screen and (max-width: 640px)" rel="alternate"/>
<link href="https://rss.netkeiba.com/?pid=rss_netkeiba&amp;site=netkeiba" rel="alternate" type="application/rss+xml"/>
<link href="https://cdn.netkeiba.com/img.sp/common/img/common/icon_home.png" rel="apple-touch-icon"/>
<!-- Google Tag Manager -->
<script>
window.dataLayer = window.dataLayer || [];
dataLayer.push({
'itemInfo': '','memberRank': 'NotLogin','memberId': ''
});
</script>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K6PJT6');</script>
<!-- End Google Tag Manager -->