# コードの動作確認

## スクレイピングに失敗した馬の再スクレイピング

In [1]:
import glob
import os
from io import StringIO

import pandas as pd
from tqdm.notebook import tqdm

import my_snipets

year = "2020"
files = glob.glob(f"../../../data/rawData/raceResults/{year}*")
files.sort()

raceResults = pd.DataFrame()
for file in tqdm(files):
    dftmp = pd.read_pickle(file)
    raceResults = pd.concat([raceResults,dftmp])

horseIDList = raceResults["horseID"].unique().tolist()
horseIDList.sort()

misshorseIDList = []
for horseID in tqdm(horseIDList):
    if os.path.isfile(f"../../../data/rawData/horse/{horseID}.pickle") == False:
        try:
            with open(f"../../../data/html/horse/{horseID}.txt","r",encoding="utf-8") as f:
                html = f.read()

            #htmlから過去戦績のデータを抽出
            contents = pd.read_html(StringIO(html))
            if len(contents) < 3 :
                horseResults = pd.DataFrame(columns=my_snipets.getHorseResultsColumns())
            elif contents[2].columns[0] == "日付":
                horseResults = contents[2]
            else:
                horseResults = contents[3]
            
            #データフレームをpickle形式で保存
            horseResults.to_pickle(f"../../../data/rawData/horse/{horseID}.pickle")
        except IndexError:
            misshorseIDList.append(horseID)

  0%|          | 0/3456 [00:00<?, ?it/s]

In [4]:
#raceCardDFのhorseIDのデータを作成
from makeRawData import makeHorseData
MHD = makeHorseData(misshorseIDList)
MHD.getHorseHTML(skipResult=False, skipPED=False)
MHD.makeHorseRawData()

1頭の馬の過去成績/血統情報データを作成します。

getHorseHTML: 100%|██████████| 1/1 [00:05<00:00,  5.01s/it, horseID=2016105739(血統情報)]
makeHorseRawData: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s, horseID=2016105739(血統情報)]

1頭の馬の過去成績/血統表データを作成しました。

## 1頭毎用

In [23]:
from makeRawData import makeHorseData
horseID = "2018110145"
#raceCardDFのhorseIDのデータを作成
from makeRawData import makeHorseData
MHD = makeHorseData([horseID])
MHD.getHorseHTML(skipResult=False, skipPED=False)
MHD.makeHorseRawData()

1頭の馬の過去成績/血統情報データを作成します。

getHorseHTML: 100%|██████████| 1/1 [00:04<00:00,  4.25s/it, horseID=2018110145(血統情報)]
makeHorseRawData: 100%|██████████| 1/1 [00:00<00:00,  2.73it/s, horseID=2018110145(過去成績)]

1頭の馬の過去成績/血統表データを作成しました。

In [24]:
from io import StringIO
import pandas as pd
dftmp = pd.read_pickle(f"../../../data/rawData/horse/{horseID}.pickle")
dftmp

,日付,開催,天 気,R,レース名,映 像,頭 数,枠 番,馬 番,オ ッ ズ,人 気,着 順,騎手,斤 量,距離,水分量,馬 場,馬場 指数,タイム,着差,ﾀｲﾑ 指数,通過,ペース,上り,馬体重,厩舎 ｺﾒﾝﾄ,備考,勝ち馬 (2着馬),賞金
0,2025/02/22,佐賀,曇,11,麗月賞,NaN,9,1,1,28.8,5.0,中,出水拓人,56,ダ1400,NaN,良,**,NaN,NaN,**,3-3-3-9,NaN,NaN,491(-3),NaN,NaN,ネオシエル,NaN
1,2025/02/08,佐賀,晴,5,唐津湾賞,NaN,7,4,4,27.6,5.0,6,金山昇馬,56,ダ1300,NaN,重,**,1:24.5,1.9,**,6-7-7-6,NaN,38.7,494(-3),NaN,NaN,ネオシエル,NaN
2,2025/01/12,佐賀,晴,9,ガーネット賞(A1),NaN,11,1,1,2.8,2.0,6,飛田愛斗,56,ダ1400,NaN,稍,**,1:30.1,1.0,**,8-8-8-8,NaN,37.2,497(+15),NaN,NaN,テイエムフォンテ,NaN
3,2024/12/08,佐賀,晴,9,暮古月賞(A1),NaN,7,4,4,3.4,2.0,1,石川倭,56,ダ1400,NaN,良,**,1:28.4,-0.1,**,3-3-2-2,NaN,37.7,482(-8),NaN,NaN,(フェブキラナ),88.0
4,2024/07/31,門別,晴,12,旭岳賞〔H3〕(重賞),NaN,8,5,5,14.1,2.0,5,石川倭,57,ダ1600,NaN,稍,**,1:43.3,2.0,**,3-4-3-2,NaN,40.5,490(-11),NaN,NaN,ベルピット,35.0
5,2024/07/13,佐賀,曇,5,遠賀川賞(OP),NaN,8,4,4,6.5,2.0,3,飛田愛斗,56,ダ1400,NaN,不,**,1:27.8,0.2,**,4-4-5-4,NaN,38.2,501(+6),NaN,NaN,フェブキラナ,43.2
6,2024/06/16,佐賀,晴,5,佐賀がばいスプリント(重賞),NaN,11,6,7,4.1,3.0,8,石川慎将,56,ダ1300,NaN,良,**,1:24.1,2.8,**,7-7-6-5,NaN,39.4,495(0),NaN,NaN,テイエムフェロー,NaN
7,2024/06/02,佐賀,曇,5,錦江湾特別(A1),NaN,7,7,7,3.1,2.0,1,飛田愛斗,56,ダ1400,NaN,良,**,1:29.5,-1.4,**,5-6-4-1,NaN,38.9,495(-1),NaN,NaN,(テイエムサウスダン),220.0
8,2024/04/29,笠松,曇,12,飛山濃水杯(重賞),NaN,12,1,1,22.4,8.0,8,飛田愛斗,57,ダ1400,NaN,良,**,1:27.2,1.9,**,8-10-10,NaN,38.0,496(0),NaN,NaN,セイルオンセイラー,NaN
9,2024/03/10,佐賀,晴,8,九州クラウン(重賞),NaN,12,1,1,23.8,5.0,2,山田義貴,56,ダ1400,NaN,稍,**,1:28.6,0.7,**,5-6-6-7,NaN,38.6,496(-4),NaN,NaN,ジョンソンテソーロ,140.0
10,2024/02/10,佐賀,晴,8,唐津湾賞,NaN,7,5,5,4.3,3.0,1,山田義貴,56,ダ1400,NaN,重,**,1:30.0,0.0,**,3-3-5-4,NaN,39.9,500(+6),NaN,NaN,(ロトヴィグラス),220.0
11,2024/01/13,佐賀,晴,11,オッズパーク・ウイン,NaN,9,2,2,4.3,2.0,1,石川慎将,56,ダ1400,NaN,良,**,1:29.7,-0.3,**,4-4-5-2,NaN,37.7,494(-4),NaN,NaN,(リョーノテソーロ),85.0
12,2023/12/23,佐賀,曇,5,玄界灘賞,NaN,11,2,2,10.2,4.0,3,飛田愛斗,56,ダ1400,NaN,重,**,1:27.7,0.3,**,6-6-6-2,NaN,37.6,498(+2),NaN,NaN,リーチ,39.6
13,2023/11/26,佐賀,晴,6,ウインターチャンピオ(重賞),NaN,12,5,6,42.7,6.0,6,飛田愛斗,56,ダ1400,NaN,良,**,1:28.1,1.1,**,8-8-8-8,NaN,37.8,496(-2),NaN,NaN,ロンドンテソーロ,NaN
14,2023/11/11,佐賀,晴,4,有明海賞(A1),NaN,9,2,2,26.8,7.0,2,飛田愛斗,56,ダ1400,NaN,良,**,1:28.9,0.6,**,3-2-2-1,NaN,39.0,498(+8),NaN,NaN,キングキャヴィア,70.4
15,2023/05/28,佐賀,晴,5,北山湖特別(A1),NaN,9,8,8,19.3,5.0,6,竹吉徹,56,ダ1300,NaN,良,**,1:23.7,0.9,**,4-5-5-5,NaN,38.4,490(+3),NaN,NaN,ダイリンウルフ,NaN
16,2023/05/13,佐賀,雨,4,錦江湾特別(A1),NaN,12,4,4,4.6,2.0,5,田中直人,56,ダ1400,NaN,重,**,1:30.0,0.7,**,11-11-11-9,NaN,39.3,487(-6),NaN,NaN,ダイリンウルフ,16.0
17,2023/04/29,佐賀,雨,4,高千穂峰賞,NaN,12,7,10,6.5,3.0,3,竹吉徹,56,ダ1860,NaN,不,**,2:03.0,1.6,**,8-8-7-4,NaN,40.2,493(+8),NaN,NaN,フェブキラナ,39.6
18,2023/03/26,佐賀,曇,6,九州クラウン(重賞),NaN,9,4,4,NaN,NaN,除,真島大輔,56,ダ1400,NaN,不,**,NaN,NaN,**,NaN,NaN,NaN,計不,NaN,NaN,リュウノシンゲン,NaN
19,2023/03/12,佐賀,雨,9,はがくれ大賞典(重賞),NaN,10,8,9,5.8,2.0,7,石川倭,56,ダ2000,NaN,稍,**,2:15.0,4.4,**,6-7-8-8,NaN,43.2,485(0),NaN,NaN,グリードパルフェ,NaN
20,2023/02/11,佐賀,曇,7,九重連山賞,NaN,9,5,5,1.1,1.0,1,飛田愛斗,56,ダ1800,NaN,重,**,1:59.1,-0.6,**,3-4-3-1,NaN,38.7,485(+3),NaN,NaN,(アエノエンペラー),200.0
21,2022/12/28,6阪神9,晴,9,春待月賞(2勝クラス),NaN,16,6,12,4.0,2.0,4,松若風馬,57,ダ1400,NaN,良,**,1:25.2,0.7,**,10-10,34.2-38.1,37.4,482(0),NaN,NaN,イフティファール,230.0
22,2022/11/05,5東京1,晴,9,神奈川新聞杯(2勝クラス),NaN,16,7,13,2.7,1.0,8,Ｍ．デム,57,ダ1600,NaN,良,**,1:37.4,0.8,**,5-4,35.7-36.4,36.8,482(0),NaN,NaN,ライラボンド,NaN
23,2022/10/16,4東京5,曇,8,3歳以上2勝クラス,NaN,15,2,2,2.1,1.0,2,菅原明良,57,ダ1600,NaN,良,**,1:37.2,0.6,**,6-6,35.1-36.4,36.2,482(0),NaN,NaN,エコロファルコン,440.0
24,2022/06/25,3東京7,晴,10,日野特別(2勝クラス),NaN,16,3,6,3.3,2.0,2,Ｍ．デム,57,ダ1600,NaN,良,**,1:36.5,0.1,**,4-4,35.9-36.5,36.3,482(+6),NaN,NaN,ロードシュトローム,611.0
25,2022/04/24,2東京2,雨,12,4歳以上2勝クラス,NaN,16,8,15,7.3,5.0,2,Ｍ．デム,57,ダ1600,NaN,稍,**,1:36.0,0.1,**,6-5,33.5-37.5,36.6,476(-2),NaN,NaN,グランツアーテム,440.0
26,2022/02/27,1阪神6,晴,6,4歳以上1勝クラス,NaN,16,3,5,2.1,1.0,1,松若風馬,57,ダ1400,NaN,良,**,1:25.5,-0.2,**,5-4,35.1-37.9,37.4,478(0),NaN,NaN,(スナークシュンソウ),770.0
27,2022/01/10,1中京4,晴,12,4歳以上1勝クラス,NaN,15,4,7,3.6,2.0,3,松山弘平,56,ダ1400,NaN,良,**,1:24.7,0.4,**,9-9,34.3-37.7,37.2,478(+2),NaN,NaN,エイシンギアアップ,190.0
28,2021/11/21,5阪神6,晴,7,3歳以上1勝クラス,NaN,16,2,3,4.1,2.0,5,松山弘平,56,ダ1400,NaN,良,**,1:25.4,0.9,**,4-7,35.2-36.7,37.0,476(0),NaN,NaN,メディーヴァル,76.0
29,2021/05/16,2東京8,曇,10,青竜S(OP),NaN,12,7,10,12.2,5.0,10,松山弘平,56,ダ1600,NaN,良,**,1:37.7,1.6,**,4-4,34.9-36.7,37.6,476(+2),NaN,NaN,ゲンパチフォルツァ,NaN
30,2021/04/24,2東京1,晴,6,3歳1勝クラス,NaN,14,6,10,4.0,2.0,2,Ｍ．デム,56,ダ1600,NaN,良,**,1:37.5,0.0,**,3-3,35.4-37.7,36.7,474(-2),NaN,NaN,レオカクテル,290.0
31,2021/03/13,2中京1,曇,10,昇竜S(OP),NaN,13,5,6,31.1,9.0,3,松山弘平,56,ダ1400,NaN,不,**,1:23.8,0.2,**,10-8,34.0-37.9,37.3,476(+6),NaN,NaN,カレンロマチェンコ,454.2
32,2020/12/13,6阪神4,曇,1,2歳未勝利,NaN,14,6,10,1.5,1.0,1,松山弘平,55,ダ1400,NaN,良,**,1:26.1,-0.1,**,7-6,34.9-38.4,37.8,470(0),NaN,NaN,(キリーティー),510.0
33,2020/11/01,4京都8,晴,4,2歳新馬,NaN,15,6,10,2.0,1.0,2,松山弘平,55,ダ1400,NaN,良,**,1:26.5,0.1,**,7-2,36.8-36.8,36.4,470(0),NaN,NaN,サステナブル,280.0

# predictionの開発

In [1]:
import datetime
import glob
from io import StringIO
#import os
import random
import re
import time
import pickle

import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.chrome.options import Options

import chromedriver_binary

import chainer
import chainer.functions as F
import chainer.links as L
from chainer import serializers

import my_snipets

## 出馬表の取得と加工

In [1]:
from prediction import makeRaceCardData
import datetime
import pandas as pd

In [2]:
tgtyear = 2025
tgtmonth = 9
tgtday = 15

In [3]:
mRCD = makeRaceCardData(datetime.date(tgtyear, tgtmonth, tgtday))
mRCD.makeRaceDateURLList()
mRCD.makeRaceURLList()
raceID = mRCD.screpingRaceCardHTML(raceNo=0)
raceCardDF = mRCD.makeRaceCardDataFrame(raceNo=0)

pd.set_option('display.max_columns', raceCardDF.shape[1])
raceCardDF

対象日付: 20250915
レース数: 24
[raceID:202509040501]出馬表のHTMLをスクレイピングしました。

,枠,馬 番,印,馬名,性齢,斤量,騎手,厩舎,馬体重 (増減),オッズ 更新,人気,登録,グループ,馬メモ切替,raceID,horseID,jockeyID,raceName,course_len,weather,raceType,groundState,date
0,1,1,--,ポッドエルマー,牡3,58.0,大江圭,美浦加藤和,NaN,22.4,6,NaN,NaN,編集,202509040501,2022105955,01120,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15
1,2,2,--,テーオーリカード,セ5,60.0,小野寺,栗東高柳大,NaN,2.2,2,NaN,NaN,編集,202509040501,2020106884,01123,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15
2,3,3,--,アンノウンウォリア,牡6,60.0,黒岩,栗東平田,NaN,14.1,4,NaN,NaN,編集,202509040501,2019100577,01072,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15
3,4,4,--,ヴィンテージボンド,牡6,60.0,難波,栗東西園正,NaN,8.2,3,NaN,NaN,編集,202509040501,2019105095,01066,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15
4,5,5,--,アメリカンエール,セ7,60.0,高田,栗東東田,NaN,16.5,5,NaN,NaN,編集,202509040501,2018110132,01046,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15
5,6,6,--,ロードプレジール,牡7,60.0,小牧加,栗東佐藤悠,NaN,2.0,1,NaN,NaN,編集,202509040501,2018102576,01196,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15
6,7,7,--,リプレイ,牝4,58.0,草野,美浦戸田,NaN,36.4,7,NaN,NaN,編集,202509040501,2021104371,01113,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15

In [9]:
mRCD.urlDF

                                                  URL            datetime
0   https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 09:45:00
1   https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 10:00:00
2   https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 10:20:00
3   https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 10:35:00
4   https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 10:50:00
5   https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 11:05:00
6   https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 11:20:00
7   https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 11:35:00
8   https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 12:10:00
9   https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 12:25:00
10  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 12:40:00
11  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 12:55:00
12  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 13:10:00
13  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 13:25:00
14  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 13:40:00
15  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 13:55:00
16  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 14:15:00
17  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 16:10:00
18  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 16:30:00
19  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 23:59:00
20  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 23:59:00
21  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 23:59:00
22  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 23:59:00
23  https://race.netkeiba.com//race/shutuba.html?r... 2025-09-15 23:59:00

## 予測用データの作成

In [4]:
#raceCardDFのhorseIDのデータを作成
from makeRawData import makeHorseData
MHD = makeHorseData(raceCardDF["horseID"].tolist())
MHD.getHorseHTML(skipResult=False)
MHD.makeHorseRawData()

7頭の馬の過去成績/血統情報データを作成します。

getHorseHTML:   0%|          | 0/7 [00:00<?, ?it/s]

getHorseHTML: 100%|██████████| 7/7 [00:11<00:00,  1.64s/it, horseID=2021104371(過去成績)]
makeHorseRawData: 100%|██████████| 7/7 [00:03<00:00,  2.30it/s, horseID=2021104371(過去成績)]

7頭の馬の過去成績/血統表データを作成しました。

In [5]:
from preprocessing import preprocessingRaceCard
pRC = preprocessingRaceCard(raceCardDF)
pRC.raceCardPreprocess()
pRC.makedataHorseResults()
pRC.horseResultsPreprocess()
pRC.makeVarFromHorseResults()
forScoringDF = pRC.forScoringDFPreprocess()

pd.set_option('display.max_columns', forScoringDF.shape[1])
forScoringDF

(7/7)

,枠番,馬番,斤量,単勝,人気,course_len,weather,raceType,groundState,Sex,Age,Weight,WeightVariation,pre1Rank,pre2Rank,pre3Rank,pre4Rank,pre5Rank,preAllRankMean,pre1Term,pre2Term,pre3Term,pre4Term,pre5Term
0,1,1,58.0,22.4,6,2970,2,2,2,2,3,-1.0,-1.0,8.0,14.0,13.0,11.0,11.0,10.500000,29.0,78.0,13.0,63.0,140.0
1,2,2,60.0,2.2,2,2970,2,2,2,0,5,-1.0,-1.0,3.0,16.0,16.0,12.0,13.0,6.687500,169.0,56.0,119.0,57.0,98.0
2,3,3,60.0,14.1,4,2970,2,2,2,2,6,-1.0,-1.0,16.0,8.0,5.0,8.0,3.0,7.826087,58.0,187.0,29.0,36.0,26.0
3,4,4,60.0,8.2,3,2970,2,2,2,2,6,-1.0,-1.0,16.0,15.0,9.0,9.0,1.0,6.705882,85.0,84.0,50.0,49.0,56.0
4,5,5,60.0,16.5,5,2970,2,2,2,0,7,-1.0,-1.0,9.0,12.0,8.0,10.0,9.0,7.357143,22.0,176.0,76.0,50.0,13.0
5,6,6,60.0,2.0,1,2970,2,2,2,2,7,-1.0,-1.0,6.0,2.0,5.0,7.0,10.0,5.440000,22.0,56.0,21.0,49.0,21.0
6,7,7,58.0,36.4,7,2970,2,2,2,1,4,-1.0,-1.0,11.0,13.0,10.0,11.0,5.0,10.375000,36.0,21.0,274.0,21.0,35.0

## 予測の実施と配信

In [6]:
from prediction import predLGBM, predNN, predDelivery

In [7]:
# lightGBMによる予測
pLGBM = predLGBM("LGBM_1", forScoringDF, raceCardDF)
pLGBM.loadModel()
raceCardDF = pLGBM.pred()

# NNによる予測
pNN = predNN("NN_1", forScoringDF, raceCardDF)
pNN.loadModel()
raceCardDF = pNN.pred()

pd.set_option('display.max_columns', raceCardDF.shape[1])
raceCardDF

,枠,馬番,印,馬名,性齢,斤量,騎手,厩舎,馬体重(増減),オッズ更新,人気,登録,グループ,馬メモ切替,raceID,horseID,jockeyID,raceName,course_len,weather,raceType,groundState,date,Sex,Age,Weight,WeightVariation,predLGBM,predNN
0,1,1,--,ポッドエルマー,牡3,58.0,大江圭,美浦加藤和,NaN,22.4,6,NaN,NaN,編集,202509040501,2022105955,01120,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15,牡,3,NaN,NaN,0.200085,0.034896
1,2,2,--,テーオーリカード,セ5,60.0,小野寺,栗東高柳大,NaN,2.2,2,NaN,NaN,編集,202509040501,2020106884,01123,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15,セ,5,NaN,NaN,0.686263,0.708484
2,3,3,--,アンノウンウォリア,牡6,60.0,黒岩,栗東平田,NaN,14.1,4,NaN,NaN,編集,202509040501,2019100577,01072,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15,牡,6,NaN,NaN,0.256319,0.070080
3,4,4,--,ヴィンテージボンド,牡6,60.0,難波,栗東西園正,NaN,8.2,3,NaN,NaN,編集,202509040501,2019105095,01066,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15,牡,6,NaN,NaN,0.363136,0.252682
4,5,5,--,アメリカンエール,セ7,60.0,高田,栗東東田,NaN,16.5,5,NaN,NaN,編集,202509040501,2018110132,01046,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15,セ,7,NaN,NaN,0.237428,0.080402
5,6,6,--,ロードプレジール,牡7,60.0,小牧加,栗東佐藤悠,NaN,2.0,1,NaN,NaN,編集,202509040501,2018102576,01196,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15,牡,7,NaN,NaN,0.725937,0.797802
6,7,7,--,リプレイ,牝4,58.0,草野,美浦戸田,NaN,36.4,7,NaN,NaN,編集,202509040501,2021104371,01113,3歳以上障害未勝利,2970,晴,障害,良,2025-09-15,牝,4,NaN,NaN,0.098865,0.013926

- 予測結果は後続の馬券購入処理に使用するので保存が必要

In [8]:
pDeli = predDelivery(raceID, raceCardDF)
pDeli.makeRaceInfoText()
pDeli.makePredText(5)
pDeli.delivaryPredLine()

## 全体実行用コードの開発

In [ ]:
from prediction import makeRaceCardData
import datetime
import pandas as pd

from makeRawData import makeHorseData
from preprocessing import preprocessingRaceCard
from prediction import predLGBM, predNN, predDelivery

tgtyear = 2025
tgtmonth = 9
tgtday = 15

mRCD = makeRaceCardData(datetime.date(tgtyear, tgtmonth, tgtday))
mRCD.makeRaceDateURLList()
mRCD.makeRaceURLList()
raceID = mRCD.screpingRaceCardHTML(raceNo=0)
raceCardDF = mRCD.makeRaceCardDataFrame(raceNo=0)

MHD = makeHorseData(raceCardDF["horseID"].tolist())
MHD.getHorseHTML(skipResult=False)
MHD.makeHorseRawData()

pRC = preprocessingRaceCard(raceCardDF)
pRC.raceCardPreprocess()
pRC.makedataHorseResults()
pRC.horseResultsPreprocess()
pRC.makeVarFromHorseResults()
forScoringDF = pRC.forScoringDFPreprocess()

# lightGBMによる予測
pLGBM = predLGBM("LGBM_1", forScoringDF, raceCardDF)
pLGBM.loadModel()
raceCardDF = pLGBM.pred()

# NNによる予測
pNN = predNN("NN_1", forScoringDF, raceCardDF)
pNN.loadModel()
raceCardDF = pNN.pred()

pDeli = predDelivery(raceID, raceCardDF)
pDeli.makeRaceInfoText()
pDeli.makePredText(5)
pDeli.delivaryPredLine()

In [ ]:
import datetime

import pandas as pd

from makeRawData import makeHorseData
from preprocessing import preprocessingRaceCard
from prediction import makeRaceCardData, predLGBM, predNN, predDelivery

tgtyear = 2025
tgtmonth = 9
tgtday = 15

mRCD = makeRaceCardData(datetime.date(tgtyear, tgtmonth, tgtday))
mRCD.makeRaceDateURLList()
mRCD.makeRaceURLList()

runtimeList = []
for tgt in mRCD.urlDF["datetime"]:
    runtime = tgt + datetime.timedelta(minutes=-3)
    runtimeList.append(runtime)

for idx, runtime in enumerate(runtimeList):
    returnflg = 0
    while returnflg == 0:
        now = datetime.datetime.now()
        if now.hour == runtime.hour and now.minute == runtime.minute :
            raceID = mRCD.screpingRaceCardHTML(raceNo=idx)
            raceCardDF = mRCD.makeRaceCardDataFrame(raceNo=idx)

            MHD = makeHorseData(raceCardDF["horseID"].tolist())
            MHD.getHorseHTML(skipResult=False)
            MHD.makeHorseRawData()

            pRC = preprocessingRaceCard(raceCardDF)
            pRC.raceCardPreprocess()
            pRC.makedataHorseResults()
            pRC.horseResultsPreprocess()
            pRC.makeVarFromHorseResults()
            forScoringDF = pRC.forScoringDFPreprocess()

            # lightGBMによる予測
            pLGBM = predLGBM("LGBM_1", forScoringDF, raceCardDF)
            pLGBM.loadModel()
            raceCardDF = pLGBM.pred()

            # NNによる予測
            pNN = predNN("NN_1", forScoringDF, raceCardDF)
            pNN.loadModel()
            raceCardDF = pNN.pred()

            pDeli = predDelivery(raceID, raceCardDF)
            pDeli.makeRaceInfoText()
            pDeli.makePredText(5)
            pDeli.delivaryPredLine()
            returnflg = 1
        else:
            time.sleep(30)

対象日付: 20250915
レース数: 24

In [7]:
runtimeList = []
for tgt in mRCD.urlDF["datetime"]:
    runtime = tgt + datetime.timedelta(minutes=-3)
    runtimeList.append(runtime)

In [8]:
runtimeList

[Timestamp('2025-09-15 09:42:00'),
 Timestamp('2025-09-15 09:57:00'),
 Timestamp('2025-09-15 10:17:00'),
 Timestamp('2025-09-15 10:32:00'),
 Timestamp('2025-09-15 10:47:00'),
 Timestamp('2025-09-15 11:02:00'),
 Timestamp('2025-09-15 11:17:00'),
 Timestamp('2025-09-15 11:32:00'),
 Timestamp('2025-09-15 12:07:00'),
 Timestamp('2025-09-15 12:22:00'),
 Timestamp('2025-09-15 12:37:00'),
 Timestamp('2025-09-15 12:52:00'),
 Timestamp('2025-09-15 13:07:00'),
 Timestamp('2025-09-15 13:22:00'),
 Timestamp('2025-09-15 13:37:00'),
 Timestamp('2025-09-15 13:52:00'),
 Timestamp('2025-09-15 14:12:00'),
 Timestamp('2025-09-15 16:07:00'),
 Timestamp('2025-09-15 16:27:00'),
 Timestamp('2025-09-15 23:56:00'),
 Timestamp('2025-09-15 23:56:00'),
 Timestamp('2025-09-15 23:56:00'),
 Timestamp('2025-09-15 23:56:00'),
 Timestamp('2025-09-15 23:56:00')]